src/app/eggly-app.js
src/index.html

Bug was in resetCreateForm() with category: $scope.currentCategory.name.

updated to angular 1.4.1 and fixed category form bug.

---

src/index.html

Updated angular to 1.5.0-rc.0 on 00-architecture-start

---

src/index.html

Updated angular to 1.5.0-rc.0 on 01-file-structure

---

src/index.html

Updated angular to 1.5.0-rc.0 on 02-sub-modules

---

src/app/categories/bookmarks/bookmarks.tmpl.html
src/app/categories/categories.js
src/app/categories/categories.tmpl.html
src/app/eggly-app.js
src/index.html

Updated angular to 1.5.0-rc.0 on 04-ui-router-named-states

---

src/index.html

Updated angular to 1.5.0-rc.0 on 11-edit-create-states

---

src/app/eggly-app.js
src/index.html

@ijones16, For some reason I can't assign this to you but heres the working version

Updated to Angular 1.5.0-rc.0 and updated to 'controller as' syntax

---

src/app/eggly-app.js
src/index.html

@ijones16, Here is the working, updated version.

Updated Angular to 1.5.0-rc.0 and added 'controller as' syntax

---

src/app/categories/categories.tmpl.html
src/app/eggly-app.js
src/index.html

Updated AngularJS to 1.5.0-rc.0 and added 'controller as' syntax

---

src/app/categories/bookmarks/bookmarks.js
src/app/categories/bookmarks/bookmarks.tmpl.html
src/app/categories/categories.tmpl.html
src/app/eggly-app.js
src/index.html

Updated angular to 1.5.0-rc.0 on 05-ui-router-state-params

---

src/app/categories/bookmarks/bookmarks.js
src/app/categories/bookmarks/bookmarks.tmpl.html
src/app/categories/categories.js
src/app/categories/categories.tmpl.html
src/app/eggly-app.js
src/index.html

Updated angular to 1.5.0-rc.0 on 06-ui-router-state-navigation

---

src/app/categories/bookmarks/bookmarks.tmpl.html
src/app/categories/categories.tmpl.html
src/app/eggly-app.js
src/index.html

Updated angular to 1.5.0-rc.0 on 07-controller-as-syntax

---

src/index.html

Updated angular to 1.5.0-rc.0 on 12-create-bookmark

---

src/index.html

Updated angular to 1.5.0-rc.0 on 13-edit-bookmark

---

src/index.html

Updated angular to 1.5.0-rc.0 on 14-delete-bookmark

---

src/index.html

Updated angular to 1.5.0-rc.0 on 15-animate-ui-router

---

src/app/categories/bookmarks/bookmarks.tmpl.html

Transitions to the appropriate category's state when a bookmark is edited.

fix(edit state): go to category on bookmark edit

---

src/app/categories/bookmarks/bookmarks.tmpl.html
src/app/categories/categories.tmpl.html
src/app/eggly-app.js
src/index.html

Updated angular to 1.5.0-rc.0 on 08-model-promotion

---

src/app/categories/bookmarks/bookmarks.tmpl.html
src/app/categories/categories.tmpl.html
src/app/eggly-app.js
src/index.html

Updated angular to 1.5.0-rc.0 on 09-http-service

---

src/app/categories/bookmarks/bookmarks.tmpl.html
src/app/categories/categories.tmpl.html
src/app/eggly-app.js
src/index.html

Updated angular to 1.5.0-rc.0 on 10-promises

---

src/index.html

Sorry @ijones16, forgot to PR this one.

Updated Angular to 1.5.5 on 05-ui-router-state-params
